# yml file to create conda environment for mapping data to the 
# Human Lung Cell Atlas using scArches
name: HLCA_mapping_env

dependencies:
 - python=3.7
 - pip
 - pip:
   - jupyterlab
   - scanpy>=1.8.2
   - torch>=1.3,<=1.8.0
   - scarches==0.3.5
   - scvi-tools==0.8.1
   - umap-learn>=0.5.2
   - pynndescent #>=0.5.5

